name: example
description: Santo UI 组件库示例 App
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.13.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  santo_ui:
    path: ../
  lpinyin: ^2.0.3
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/china.json
    - assets/
    - assets/image/
    - assets/icons/
